default: compile run1

compile:
	g++ -std=c++11 -o hw4 hw4.cpp
run1: compile
	./hw4 -f hw4_1.ps
run2: compile
	./hw4 -f hw4_2.ps
run3: compile
	./hw4 -f hw4_3.ps
run5: compile
	./hw4 -f hw4_5.ps
run4: compile
	./hw4 -f hw4_4.ps
run6: compile
	./hw4 -f hw4_6.ps
run7: compile
	./hw4 -f hw4_7.ps
run8: compile
	./hw4 -f hw4_8.ps
run9: compile
	./hw4 -f hw4_9.ps
compilegdb:
	g++ -std=c++11 -g hw4.cpp
all: compile run1 run2 run3 run4 run5 run6 run7 run8 run9
