default: compile run3_1

compile:
	g++ -std=c++11 -o hw3 hw3.cpp
run3_1: compile
	./hw3 -f hw3_1.ps
run3_2: compile
	./hw3 -f hw3_2.ps
run3_3: compile
	./hw3 -f hw3_3.ps
run3_5: compile
	./hw3 -f hw3_5.ps
run3_4: compile
	./hw3 -f hw3_4.ps
run3_6: compile
	./hw3 -f hw3_6.ps
run3_7: compile
	./hw3 -f hw3_7.ps
compilegdb:
	g++ -std=c++11 -g hw3.cpp
all: compile run3_1 run3_2 run3_3 run3_4 run3_5 run3_6 run3_7
